services:
  dev1:
    image: ${DOCKER_IMAGE:-node:18.17.1}
    tty: true
    stdin_open: true
    volumes:
      - ./agents/dev1/codebase:/home/${DOCKER_USER}/codebase
      - ./agents/dev1/claude/.claude:/home/${DOCKER_USER}/.claude
      - ./agents/dev1/claude/.claude.json:/home/${DOCKER_USER}/.claude.json
      - ./entrypoint.sh:/home/${DOCKER_USER}/entrypoint.sh:ro
    environment:
      IS_SANDBOX: 1 # for claude code to work on the ${DOCKER_USER} user
      GITHUB_REPO: ${GITHUB_REPO}
      GH_TOKEN: ${DEV1_GITHUB_TOKEN}
      AGENT_NAME: ${DEV1_AGENT_NAME}
      AGENT_PROMPT: ${DEV1_PROMPT}
      COMMON_PROMPT: ${COMMON_PROMPT}
    entrypoint: [ "/home/${DOCKER_USER}/entrypoint.sh" ]
  arch1:
    image: ${DOCKER_IMAGE:-node:18.17.1}
    tty: true
    stdin_open: true
    volumes:
      - ./agents/arch1/codebase:/home/${DOCKER_USER}/codebase
      - ./agents/arch1/claude/.claude:/home/${DOCKER_USER}/.claude
      - ./agents/arch1/claude/.claude.json:/home/${DOCKER_USER}/.claude.json
      - ./entrypoint.sh:/home/${DOCKER_USER}/entrypoint.sh:ro
    environment:
      IS_SANDBOX: 1 # for claude code to work on the ${DOCKER_USER} user
      GITHUB_REPO: ${GITHUB_REPO}
      GH_TOKEN: ${ARCH1_GITHUB_TOKEN}
      AGENT_PROMPT: ${ARCH1_PROMPT}
      AGENT_NAME: ${ARCH1_AGENT_NAME}
      COMMON_PROMPT: ${COMMON_PROMPT}
    entrypoint: [ "/home/${DOCKER_USER}/entrypoint.sh" ]
